parent(pam,bob).
parent(tom,bob).
parent(tom,liz).
parent(bob,ann).
parent(bob,pat).
parent(liz,joe).
parent(joe,jim).
parent(pat,jim).
female(pam).
female(liz).
female(ann).
female(pat).
male(tom).
male(bob).
male(joe).
male(jim).
child(X,Y):-parent(X,Y).
mother(X,Y):-parent(X,Y),female(X).
father(X,Y):-parent(X,Y),male(Y).
ancestor(X,Z):-parent(X,Z).
ancestor(X,Z):-parent(X,Y),ancestor(Y,Z).
sibling(X,Y):-parent(Z,X),parent(Z,Y).
sister(X,Y):-sibling(X,Y),female(X).
brother(X,Y):-sibling(X,Y),male(X).
grandparent(X,Z):-parent(X,Y),parent(Y,Z).
grandmother(X,Z):-grandparent(X,Z),female(X).
grandfather(X,Z):-grandparent(X,Z),male(Z).
aunt(X,A):-sibling(Y,A),child(Y,Z),female(X).
uncle(X,A):-sibling(Y,A),child(Y,Z),male(X).
cousin(A,B):-parent(Y,A),parent(Z,B),sibling(Y,Z).